#!/usr/bin/env python3
"""
新年烟花动画 - 在终端中显示烟花发射和爆炸效果
使用纯ASCII字符确保跨平台兼容性
按任意键退出程序
"""

import curses
import random
import time
import math
import sys
import os
from collections import deque
from firework import Firework
from textrasterizer import RasterizedText, text_to_ascii
from asciidrawer import draw_ascii_art_advanced, draw_ascii_art_transparent_advanced
from torus import Torus
with open("houseascii.txt", "r") as f:
    fancy_house = f.read()

def init_colors():
    """初始化颜色对"""
    curses.start_color()
    curses.use_default_colors()
    # 定义颜色对 (1-6)
    curses.init_pair(1, curses.COLOR_RED, -1)      # 红色
    curses.init_pair(2, curses.COLOR_GREEN, -1)    # 绿色
    curses.init_pair(3, curses.COLOR_YELLOW, -1)   # 黄色
    curses.init_pair(4, curses.COLOR_BLUE, -1)     # 蓝色
    curses.init_pair(5, curses.COLOR_MAGENTA, -1)  # 洋红色
    curses.init_pair(6, curses.COLOR_CYAN, -1)     # 青色
    curses.init_pair(7, curses.COLOR_WHITE, -1)    # 白色
    # curses.init_pair(8, curses.COLOR_WHITE, -1)



def draw_background(stdscr, height, width, frame_count, raster_text):
    """绘制背景和装饰"""
    # 使用增强版函数在左侧绘制房屋（底部对齐，左对齐）


    raster_text.draw()
    draw_ascii_art_transparent_advanced(
        stdscr, 
        fancy_house, 
        position_type="bottom", 
        horizontal="center", 
        color_pair=7,  # 青色
        offset_y=0,   # 向上偏移1行
        offset_x=0     # 向右偏移5列
    )
    
def draw_watermark(stdscr, height, width, frame_count):
    text1 = "Generated by Python 3.13;"
    text2 = "Coded with care & love."
    total_cycle = frame_count % ((len(text1) + len(text2))*2)
    if total_cycle <= len(text1):
        stdscr.addstr(height-2, 0, text1[:total_cycle])
        curses.curs_set(1)
        stdscr.move(height-2, total_cycle)
    elif total_cycle <= len(text1) + len(text2):
        stdscr.addstr(height-2, 0, text1)
        stdscr.addstr(height-1, 0, text2[:total_cycle - len(text2)])
        stdscr.move(height-1, total_cycle - len(text2))
    else:
        stdscr.addstr(height-2, 0, text1)
        stdscr.addstr(height-1, 0, text2)
        curses.curs_set(0)
    
def main(stdscr):
    # 设置curses
    stdscr.nodelay(1)
    # stdscr.timeout(80)  # 稍微降低刷新率
    # 初始化颜色
    init_colors()
    
    # 获取屏幕尺寸
    height, width = stdscr.getmaxyx()
    buffer_win = curses.newwin(height, width)
    # 创建光栅化文字对象
    raster_text = RasterizedText(buffer_win, ["新年快乐", "2026"], size=19, font_path=R"C:\Windows\Fonts\STZHONGS.TTF")
    raster_text.setup()
    torus = Torus(buffer_win, height, width)
    raster_text.speed = 10
    
    # 烟花列表
    fireworks = []
    frame_time_queue = deque()
    # 帧计数器
    frame_count = 0
    
    # 主循环
    while True:
        # 清屏
        start = time.time()
        buffer_win.clear()
        
        # 检查按键
        key = stdscr.getch()
        if key != -1:
            break
        
        # 随机发射新烟花
        if len(fireworks) < 6 and random.random() < 0.15:
            fireworks.append(Firework(width, height))
        
        # 更新光栅化文字
        raster_text.update()
        torus.update(1/120)
        torus.draw()
        # 绘制背景（包括光栅化文字）
        draw_background(buffer_win, height, width, frame_count, raster_text)
        
        # 更新和绘制所有烟花
        for firework in fireworks[:]:
            firework.update(1/4)
            firework.draw(buffer_win)
            
            if firework.state == 'done':
                fireworks.remove(firework)
        
        end = time.time()
        frame_time_queue.append((end - start)*1000)
        if len(frame_time_queue) >= 500:
            frame_time_queue.popleft()
            
        text = "Rendering time: "+f"{round(sum(frame_time_queue)/len(frame_time_queue), 3)}"[::-1].zfill(6)[::-1]+" ms | " + f"{round(1000*len(frame_time_queue)/sum(frame_time_queue))}".zfill(3)+ " fps"
        buffer_win.addstr(height-1, width-len(text)-1, text)
        draw_watermark(buffer_win, height, width, frame_count)
        buffer_win.noutrefresh()
        curses.doupdate()
        time.sleep(max(1/60 - (end - start), 0))
        
        # 增加帧计数
        frame_count += 1
        
        # 控制帧率

def run_animation():
    """运行动画，处理可能的异常"""
    try:
        curses.wrapper(main)
    except KeyboardInterrupt:
        print("\n谢谢观看！新年快乐！")
        sys.exit(0)
    except Exception as e:
        print(f"运行动画时出现错误: {e}")
        print("请确保终端窗口足够大（至少20x40），然后重试。")
        sys.exit(1)

if __name__ == "__main__":
    # 检查是否为Windows系统
    if os.name == 'nt':
        print("注意：Windows系统的curses支持有限，建议使用")
        print("1. 确保终端窗口足够大（至少40列×20行）")
        print("2. 如果仍然有问题，尝试使用命令提示符(CMD)而不是PowerShell")
        print("3. 或者使用Windows Terminal应用")
        print("\n按Enter键开始动画...")
        input()
    
    run_animation()